changed the intro to recommend installing from release tar.
epics-docs/epics-docs pull request #86
Opened 2024-06-14 15:13 UTC by ttkorhonen

Tried to address issue #70 . Please review.

2024-06-14 15:36 UTC, ralphlange requested changes
Please fix the two small issues before merging.

2024-06-14 15:36 UTC, ralphlange commented on getting-started/installation-linux.rst
> +The recommended way to start working with EPICS is to download one of the released packages.
release packages

2024-06-14 15:36 UTC, ralphlange commented on getting-started/installation-linux.rst
> +    cd base-R7.0.8.1
cd base-7.0.8.1

2024-06-16 21:55 UTC, anjohnson reviewed
One minor tweak, otherwise I'm fine with this.

2024-06-16 21:55 UTC, anjohnson commented on getting-started/installation-linux.rst
> +These packages contain all the recommended submodules that have been tested to work together.
I don't see the need to mention submodules here, maybe instead use

> The released versions of EPICS have been fully tested to work as documented.

2024-06-17 06:54 UTC, merged

2024-06-18 10:24 UTC, ralphlange commented
If someone complains about that, send them to me...

2024-06-18 10:27 UTC, ttkorhonen commented
OK then! For once, documentation is ahead of implementation.

2024-06-18 22:43 UTC, anjohnson commented
Oh yes, [that](https://github.com/epics-base/epics-base/pull/491) was another thing I was in the middle of doing wasn't it. Nobody has actually approved my PR yet though, and I believe this will be our first release where the tagged release commit won't be an ancestor of all the commits that were merged after I branched but before that gets merged. That will be an interesting merge...

2024-06-19 07:27 UTC, ralphlange commented
> Oh yes, [that](https://github.com/epics-base/epics-base/pull/491) was another thing I was in the middle of doing wasn't it. Nobody has actually approved my PR yet though,

Didn't you mark that PR as "don't ever merge"? Why approve something when there's no intention to merge?
Sorry, but your procedure is as unusual as unclear.

> and I believe this will be our first release where the tagged release commit won't be an ancestor of all the commits that were merged after I branched but before that gets merged. That will be an interesting merge...

*Shrug.*
Your procedure, your rules.

2024-06-19 23:00 UTC, anjohnson commented
@ralphlange I was hoping for some feedback about the proposal, I'd rather not assume that no response from you guys means approval. The warning at the top was to ensure nobody else would actually merge the PR as committed, which would have caused a mess.