DOC reference a newer version
epics-docs/epics-docs pull request #94
Opened 2024-06-19 15:14 UTC by prjemian

Update the link to building EPICS on Raspberry Pi.  Existing link points to 2014 instructions.  Revision points to 2020 revision.

2024-06-19 15:33 UTC, minijackson commented
I haven't compared the two versions yet, but if the new tutorial is an improvement compared to the first one, is it useful keeping the old link?

2024-06-19 20:48 UTC, ttkorhonen commented
I tend to agree with @minijackson. Maybe the old link can be removed, or are there people using still the old instructions?

2024-06-19 21:32 UTC, prjemian commented
I'm happy with that

On Wed, Jun 19, 2024, 3:49 PM Timo Korhonen ***@***.***>
wrote:

> I tend to agree with @minijackson <https://github.com/minijackson>. Maybe
> the old link can be removed, or are there people using still the old
> instructions?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/epics-docs/epics-docs/pull/94#issuecomment-2179439726>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARMUMCO3TCWW7PMXXP4SJTZIHVE5AVCNFSM6AAAAABJSIQITWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNZZGQZTSNZSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-20 08:16 UTC, ttkorhonen requested changes
I would suggest just to remove the old link here; it is still available on the new page as I saw, so nothing would be lost.
Also, I see that you have done this with Sphinx, so I might change the explicit link to use intersphinx links in a subsequent edit. That would make it a bit more robust and also give a few nice possibilities for cross-referencing. But that will be later.

2024-06-20 15:03 UTC, prjemian commented
FWIW: [intersphinx links](https://docs.readthedocs.io/en/stable/guides/intersphinx.html)

2024-06-20 16:14 UTC, ttkorhonen approved these changes
Looks good to me!

2024-06-20 16:17 UTC, merged